export const AUCTION_RANDOM_REQUEST = 'AUCTION_RANDOM_REQUEST'
export const AUCTION_RANDOM_SUCCESS = 'AUCTION_RANDOM_SUCCESS'
export const AUCTION_RANDOM_FAIL = 'AUCTION_RANDOM_FAIL'

export const AUCTION_MYAUCTIONS_REQUEST = 'AUCTION_MYAUCTIONS_REQUEST'
export const AUCTION_MYAUCTIONS_SUCCESS = 'AUCTION_MYAUCTIONS_SUCCESS'
export const AUCTION_MYAUCTIONS_FAIL = 'AUCTION_MYAUCTIONS_FAIL'
