export const AUCTION_RANDOM_REQUEST = 'AUCTION_RANDOM_REQUEST'
export const AUCTION_RANDOM_SUCCESS = 'AUCTION_RANDOM_SUCCESS'
export const AUCTION_RANDOM_FAIL = 'AUCTION_RANDOM_FAIL'

export const AUCTION_MYAUCTIONS_REQUEST = 'AUCTION_MYAUCTIONS_REQUEST'
export const AUCTION_MYAUCTIONS_SUCCESS = 'AUCTION_MYAUCTIONS_SUCCESS'
export const AUCTION_MYAUCTIONS_FAIL = 'AUCTION_MYAUCTIONS_FAIL'

export const AUCTION_DELETE_REQUEST = 'AUCTION_DELETE_REQUEST'
export const AUCTION_DELETE_SUCCESS = 'AUCTION_DELETE_SUCCESS'
export const AUCTION_DELETE_FAIL = 'AUCTION_DELETE_FAIL'

export const AUCTION_DETAILS_REQUEST = 'AUCTION_DETAILS_REQUEST'
export const AUCTION_DETAILS_SUCCESS = 'AUCTION_DETAILS_SUCCESS'
export const AUCTION_DETAILS_FAIL = 'AUCTION_DETAILS_FAIL'

export const AUCTION_LIST_REQUEST = 'AUCTION_LIST_REQUEST'
export const AUCTION_LIST_SUCCESS = 'AUCTION_LIST_SUCCESS'
export const AUCTION_LIST_FAIL = 'AUCTION_LIST_FAIL'

export const AUCTION_CREATE_REQUEST = 'AUCTION_CREATE_REQUEST'
export const AUCTION_CREATE_SUCCESS = 'AUCTION_CREATE_SUCCESS'
export const AUCTION_CREATE_FAIL = 'AUCTION_CREATE_FAIL'
export const AUCTION_CREATE_RESET = 'AUCTION_CREATE_RESET'

export const AUCTION_UPDATE_REQUEST = 'AUCTION_UPDATE_REQUEST'
export const AUCTION_UPDATE_SUCCESS = 'AUCTION_UPDATE_SUCCESS'
export const AUCTION_UPDATE_FAIL = 'AUCTION_UPDATE_FAIL'
export const AUCTION_UPDATE_RESET = 'AUCTION_UPDATE_RESET'

export const AUCTION_BID_REQUEST = 'AUCTION_BID_REQUEST'
export const AUCTION_BID_SUCCESS = 'AUCTION_BID_SUCCESS'
export const AUCTION_BID_FAIL = 'AUCTION_BID_FAIL'
